site_name: KTH Date Repository Guides
site_url: https://samk13.github.io/docs-kth-rdm
repo_url: https://github.com/Samk13/docs-kth-rdm
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Figtree
  logo: assets/images/kth-logo.svg
  favicon: assets/images/favicon.ico

  palette:
    - scheme: slate
      primary: custom
    # dark theme
      toggle:
        icon: material/brightness-7
        name: Dark mode
      accent: pink

    # light theme
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: custom
      accent: pink

markdown_extensions:
# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#configuration
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# Footer

extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/kth
copyright: '© 2024 KTH Royal Institute of Technology'

nav:
  # When updating the nav, remember to update the i18n plugin as well
  - Home: index.md
  - Topic1: topic1/index.md

plugins:
  - search:
      lang: en
  # https://ultrabug.github.io/mkdocs-static-i18n/getting-started/quick-start/
  # https://github.com/squidfunk/mkdocs-material/discussions/2346
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-search/
      reconfigure_search: true
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: sv
          name: Svenska
          build: true

          # Nav Translations
          # https://ultrabug.github.io/mkdocs-static-i18n/setup/localizing-navigation/
          nav:
            - Hem: index.sv.md
            - Ämne1: topic1/index.sv.md
