site_name: KTH data Repository Guides
site_url: https://kth-library.github.io/docs-kth-rdm/
repo_url: https://github.com/KTH-Library/docs-kth-rdm
copyright: '© 2024 KTH Royal Institute of Technology'

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Figtree
  logo: assets/images/kth-logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs

  palette:
    - scheme: slate
      primary: custom
    # dark theme
      toggle:
        icon: material/brightness-7
        name: Dark mode
      accent: pink

    # light theme
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: custom
      accent: pink

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#configuration
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

# Footer
extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/kth

plugins:
  - search:
      lang: en
      # https://squidfunk.github.io/mkdocs-material/plugins/search/#config.pipeline
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  # https://ultrabug.github.io/mkdocs-static-i18n/getting-started/quick-start/
  # https://github.com/squidfunk/mkdocs-material/discussions/2346
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-search/
      reconfigure_search: true
      # Can be 'folder' or 'suffix' e.g index.sv.md
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: sv
          name: Svenska
          build: true
          # Nav Translations
          # https://ultrabug.github.io/mkdocs-static-i18n/setup/localizing-navigation/
          nav:
            - Hem: sv/index.md
            - Guider:
                - Villkor: sv/terms.md


nav:
  # When updating the nav, remember to update the i18n plugin nav as well
  - Home: index.md
  - Guides:
      - Terms: en/terms.md
