site_name: KTH Date Repository Guides
site_url: https://samk13.github.io/docs-kth-rdm
repo_url: https://github.com/Samk13/docs-kth-rdm
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Figtree
  logo: assets/images/kth-logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs

  palette:
    - scheme: slate
      primary: custom
    # dark theme
      toggle:
        icon: material/brightness-7
        name: Dark mode
      accent: pink

    # light theme
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: custom
      accent: pink

markdown_extensions:
# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#configuration
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

# Footer

extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/kth
copyright: '© 2024 KTH Royal Institute of Technology'

nav:
  # When updating the nav, remember to update the i18n plugin as well
  - Home: index.md
  - Guides:
      - Terms: terms.md
      - Community Manager Responsibilities: community_manager_responsibilities.md
      - Create Community: create_community.md
      - GitHub Integration: github_integration.md
      - How-To: how_to.md
      - REST API Reference: rest_api_reference.md
      - Restrict Record Access: restrict_record_access.md
      - Share Record Access: share_record_access.md
      - Upload Record: upload_record.md

plugins:
  - search:
      lang: en
  # https://ultrabug.github.io/mkdocs-static-i18n/getting-started/quick-start/
  # https://github.com/squidfunk/mkdocs-material/discussions/2346
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-search/
      reconfigure_search: true
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: sv
          name: Svenska
          build: true

          # Nav Translations
          # https://ultrabug.github.io/mkdocs-static-i18n/setup/localizing-navigation/
          nav:
            - Hem: index.sv.md
            - Guider:
                - Villkor: terms.sv.md
                - Ansvar för Community Manager: community_manager_responsibilities.sv.md
                - Skapa Community: create_community.sv.md
                - GitHub-integration: github_integration.sv.md
                - Hur man gör: how_to.sv.md
                - REST API Referens: rest_api_reference.sv.md
                - Begränsa Poståtkomst: restrict_record_access.sv.md
                - Dela Poståtkomst: share_record_access.sv.md
                - Ladda upp Post: upload_record.sv.md

